### ISSUE TITLE
Secondary rate limit.

### ISSUE THREAD

**Issue by funes79** [JasonEtco/create-an-issue#128]
Hi, after using this step couple of times (up to 10) I started to got:

`You have exceeded a secondary rate limit. Please wait a few minutes before you try again.`

Any idea why?
Even if  I wait couple of minutes, the next runs fails again.

```
✖  fatal     HttpError: You have exceeded a secondary rate limit. Please wait a few minutes before you try again. 
    at /home/runner/work/_actions/JasonEtco/create-an-issue/v2/dist/index.js:5310:23
    at processTicksAndRejections (internal/process/task_queues.js:[97](https://github.com/<myorg>/<repo>/runs/6961602472?check_suite_focus=true#step:9:98):5)
    at async createAnIssue (/home/runner/work/_actions/JasonEtco/create-an-issue/v2/dist/index.js:33053:32)
```

**Comment by UVLabs** [comment]
I think you should post your question here: https://github.com/dblock/create-a-github-issue

as this current library seems to be unmaintained

**Comment by JasonEtco** [comment]
Closing this due to inactivity; it's likely a problem within Actions, independent of this particular Action. If you think that's not the case, feel free to reopen!

**Comment by andys8** [comment]
I'm also randomly seeing this happening. How many API requests will this action typically execute? Depending on which config flags? Is there a known way to work around this?

I'll also investigate and try to get rid of other actions I use, but from the outside it looks more likely that it's occuring because of this action.

```
Error: You have exceeded a secondary rate limit. Please wait a few minutes before you try again.
```
