### ISSUE TITLE
Bad Credentials for GitHub Enterprise edition

### ISSUE THREAD

**Issue by Abhijeet-Pubba** [JasonEtco/create-an-issue#160]
Hey there,

I have been trying to use this action to create issues but couldn't. Steps in my `.yml` file looks something like below

```yaml
...
steps:
  - uses: actions/checkout@v3
  - name: Create Issue Action
    uses: JasonEtco/create-an-issue@v2
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      assignees: <username>
      update_existing: true
      search_existing: all
...
```

And ISSUE_TEMPLATE.md like below

```MD
---
title: "[Bug] : Something unexpected happened"
---
"A bug happened!"
```

Action is Failing with HttpError: Bad credentials for our enterprise edition

```log
debug     Reading from file .github/ISSUE_TEMPLATE.md
ℹ  info      Front matter for .github/ISSUE_TEMPLATE.md is { title: '[Bug] : Something unexpected happened' }
⬤  debug     Templates compiled {
  body: '"A bug happened!"\n',
  title: '[Bug] : Something unexpected happened'
}
ℹ  info      Fetching issues with title "[Bug] : Something unexpected happened"
Error: Bad credentials
✖  fatal     HttpError: Bad credentials 
    at /Users/apubba/Desktop/actions-runner/_work/_actions/JasonEtco/create-an-issue/v2/dist/index.js:5855:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createAnIssue (/Users/apubba/Desktop/actions-runner/_work/_actions/JasonEtco/create-an-issue/v2/dist/index.js:41271:32)
```

**Comment by ConnorDY** [comment]
I have the same issue! I might be able to contribute a PR to fix this.

**Comment by EdouardF** [comment]
Hey @JasonEtco, in my org we'd love to use this action but this is clearly a blocking issue... Any plans to fix it?
@ConnorDY any PR incoming that @JasonEtco could merge?
