### ISSUE TITLE
Malformed label error for labels including a colon

### ISSUE THREAD

**Issue by pmeier** [JasonEtco/create-an-issue#65]
We use labels might include a colon such as `module: datasets`. The label section of the issue template looks like this:

```md
labels: 
    - bug
    - "module: datasets"
```

Trying to open an issue with this template fails (see https://github.com/pytorch/vision/actions/runs/271212579 for an example):

```sh
⬤  debug     Reading from file .github/failed_schedule_issue_template.md
ℹ  info      Front matter for .github/failed_schedule_issue_template.md is { title: 'Scheduled workflow {{ env.WORKFLOW }}/{{ env.JOB }} failed',
  labels: [ 'bug', 'module: datasets' ] }
⬤  debug     Templates compiled { body:
   'Oh no, something went wrong in the scheduled workflow tests/download. \nPlease look into it:\n\nhttps://github.com/pytorch/vision/actions/runs/271212579\n\nFeel free to close this if this was just a one-off error.\n',
  title: 'Scheduled workflow tests/download failed' }
ℹ  info      Creating new issue Scheduled workflow tests/download failed
✖  error     An error occurred while creating the issue. This might be caused by a malformed issue title, or a typo in the labels or assignees. Check .github/failed_schedule_issue_template.md!
✖  error     HttpError: Resource not accessible by integration 
    at response.text.then.message (/node_modules/@octokit/request/dist-node/index.js:66:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: An error occurred while creating the issue. This might be caused by a malformed issue title, or a typo in the labels or assignees. Check .github/failed_schedule_issue_template.md!
```

It seems that label is correctly recognized as string. Thus, I assume some internal parsing is causing this.

**Comment by pmeier** [comment]
@JasonEtco I've debugged this locally and it seems the issue lies with `tools.github.issues.create`:

https://github.com/JasonEtco/create-an-issue/blob/e6b4b190af80961b6462c725454e7828d0247a68/index.js#L42-L48

I've created a local test with the same labels as above and it runs fine. Given that the GitHub API call is mocked out, I suspect the problem there. Since you are also the owner of [JasonEtco/actions-toolkit](https://github.com/JasonEtco/actions-toolkit) could you transfer this issue if my hunch is right?

**Comment by pmeier** [comment]
Ignore this. I was able to create an issue with the exact same template in a clean repository. Thus, I now suspect our repo configuration is somehow messed up. 

The only thing you could take from here is probably a better error message. I was hung up on the "unusual label" and it took me quite some time to figure out that it has nothing to do with it.
