### ISSUE TITLE
Support mustache template for title + labels

### ISSUE THREAD

**Issue by bitsofinfo** [JasonEtco/create-an-issue#74]
Support mustache template for title + labels

**Comment by JasonEtco** [comment]
Issue titles and bodies already support mustache (technically Nunjucks). Is there something specific that isn't working?

**Comment by bitsofinfo** [comment]
```
Error: can not read a block mapping entry; a multiline key may not be an implicit key at line 2, column 7:
    labels: {{ env.ACTION_NAME }}, failure
          ^
✖  fatal     YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 2, column 7: 
    labels: {{ env.ACTION_NAME }}, failure
```

**Comment by bitsofinfo** [comment]
```
---
title: {{ env.ACTION_NAME }} failure
labels: action-failure
---
something
```

```
Error: can not read a block mapping entry; a multiline key may not be an implicit key at line 2, column 7:
    labels: action-failure
          ^
✖  fatal     YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 2, column 7: 
    labels: action-failure
```

**Comment by bitsofinfo** [comment]
@JasonEtco so what I am I doing wrong above?

```
      - uses: JasonEtco/create-an-issue@v2
        id: create-issue
        if: ${{ always() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_RUN_ID: ${{ env.GITHUB_RUN_ID }}
          ACTION_NAME: ${{ github.action }}
        with:
          filename: .github/templates/issue.adhoc-run-tests.failed.md
```

**Comment by JasonEtco** [comment]
Ah that looks like a YAML problem. Strings can't start with characters like {. Try wrapping those frontmatter values in quotes.

**Comment by bitsofinfo** [comment]
@JasonEtco ok thanks that fixes the title, but what about variables for the labels?

neither of these work

```
---
title: "{{ env.ACTION_NAME }} failure"
labels: "{{ env.ACTION_NAME }}"
---
something
```

```
  title: 'JasonEtcocreate-an-issue failure' }
ℹ  info      Creating new issue JasonEtcocreate-an-issue failure
✖  error     An error occurred while creating the issue. This might be caused by a malformed issue title, or a typo in the labels or assignees. Check .github/templates/issue.adhoc-run-tests.failed.md!
✖  error     TypeError: list.split is not a function 
    at listToArray (/index.js:9:44)
    at Toolkit.run (/index.js:46:15)
    at Function.<anonymous> (/node_modules/actions-toolkit/lib/index.js:119:31)
    at step (/node_modules/actions-toolkit/lib/index.js:44:23)
    at Object.next (/node_modules/actions-toolkit/lib/index.js:25:53)
    at /node_modules/actions-toolkit/lib/index.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/node_modules/actions-toolkit/lib/index.js:15:12)
    at Function.Toolkit.run (/node_modules/actions-toolkit/lib/index.js:110:16)
    at Object.<anonymous> (/index.js:12:9)
```

**Comment by bitsofinfo** [comment]
and  @JasonEtco 

```
---
title: "{{ env.ACTION_NAME }} failure"
labels: {{ env.ACTION_NAME }}
---
something
```

just results in a literal label value that is unparsed i.e. `{{ env.ACTION_NAME }}`

**Comment by JasonEtco** [comment]
Labels aren't templateable at the moment, there just hasn't been a need for it. Right now, only the title and body get rendered by the template engine:

https://github.com/JasonEtco/create-an-issue/blob/be196d12b3cf31a85de7ba525595cb12560fc4e8/index.js#L38-L41

You're welcome to open a PR adding `labels` to that. It'd look something like:

```js
const templated = {
  // ...
  labels: listToArray(env.renderString(attributes.labels, templateVariables))
}
```

**Comment by bitsofinfo** [comment]
would be great if this can be added, thanks

**Comment by JasonEtco** [comment]
Great - I'll look out for your PR @bitsofinfo, let me know if you have any questions!
