### ISSUE TITLE
possible to use {{ env.VAR }} in template title?

### ISSUE THREAD

**Issue by tlambert03** [JasonEtco/create-an-issue#80]
I'd like to set the title of a new issue using an envar.  I tried mimicking the `Dates` example from the readme by doing the following:

```
# .github/TEST_FAIL_TEMPLATE.md
---
title: {{ env.TITLE }}
---
...
```

```
# action.yml
- name: Report Failures
  if: ${{ failure() }}
  uses: JasonEtco/create-an-issue@v2
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    TITLE: 'Comprehensive tests failing'
  with:
    filename: .github/TEST_FAIL_TEMPLATE.md
    update_existing: true
```

but I get the following error in github actions

```
⬤  debug     Reading from file .github/TEST_FAIL_TEMPLATE.md
ℹ  info      Front matter for .github/TEST_FAIL_TEMPLATE.md is { title: { '[object Object]': null }, labels: [ 'bug' ] }
Error: Unexpected template object type undefined; expected 'code', or 'string'
✖  fatal     Error: Unexpected template object type undefined; expected 'code', or 'string' 
    at Template.init (/home/runner/work/_actions/JasonEtco/create-an-issue/v2/dist/index.js:26920:17)
    at Template.Obj (/home/runner/work/_actions/JasonEtco/create-an-issue/v2/dist/index.js:29905:15)
    at new Template (/home/runner/work/_actions/JasonEtco/create-an-issue/v2/dist/index.js:26901:18)
    at Environment.renderString (/home/runner/work/_actions/JasonEtco/create-an-issue/v2/dist/index.js:26802:16)
    at createAnIssue (/home/runner/work/_actions/JasonEtco/create-an-issue/v2/dist/index.js:38344:20)
```

thanks in advance for any tips!

**Comment by tlambert03** [comment]
ahhh, sorry, I just figured it out I needed to quote the {{ env.VAR }} in the frontmatter:
```
# .github/TEST_FAIL_TEMPLATE.md
---
title: "{{ env.TITLE }}"
---
...
```
