### ISSUE TITLE
Fails creating issues.

### ISSUE THREAD

**Issue by sketabchi-mobiz** [JasonEtco/create-an-issue#83]
When using the following settings 

1) The template file *located in .github/ISSUE_TEMPLATE.md*

```
---
title: Someone just pushed
assignees: abcdef
labels: bug
---
Someone just pushed, oh no! Here's who did it: {{ payload.sender.login }}.
```
2) The action: 
```
- uses: JasonEtco/create-an-issue@v2   
   env:   
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
```

I get this error: 

![image](https://user-images.githubusercontent.com/60545316/107857826-b1a12b00-6de5-11eb-8715-9731eaf7488c.png)

```
/home/runner/work/_actions/JasonEtco/create-an-issue/v2/dist/index.js:32633
		throw jsonErr;
		^
ErrorEXError [JSONError]: Unexpected end of JSON input while parsing near '' in package.json
    at module.exports (/home/runner/work/_actions/JasonEtco/create-an-issue/v2/dist/index.js:32628:19)
    at parse (/home/runner/work/_actions/JasonEtco/create-an-issue/v2/dist/index.js:18172:29)
    at Function.module.exports.sync (/home/runner/work/_actions/JasonEtco/create-an-issue/v2/dist/index.js:18175:29)
    at Function.sync (/home/runner/work/_actions/JasonEtco/create-an-issue/v2/dist/index.js:34927:27)
    at Signale.get packageConfiguration [as packageConfiguration] (/home/runner/work/_actions/JasonEtco/create-an-issue/v2/dist/index.js:37232:20)
    at new Signale (/home/runner/work/_actions/JasonEtco/create-an-issue/v2/dist/index.js:37171:39)
    at Object.528 (/home/runner/work/_actions/JasonEtco/create-an-issue/v2/dist/index.js:37143:32)
    at __webpack_require__ (/home/runner/work/_actions/JasonEtco/create-an-issue/v2/dist/index.js:38615:43)
    at Object.7045 (/home/runner/work/_actions/JasonEtco/create-an-issue/v2/dist/index.js:4902:17)
    at __webpack_require__ (/home/runner/work/_actions/JasonEtco/create-an-issue/v2/dist/index.js:38615:43) {
  name: 'JSONError',
  fileName: 'package.json'
}
```

**Comment by JasonEtco** [comment]
I don't think this is still happening, so I'm going to close this. If I'm mistaken, feel free to reopen and I can investigate.

**Comment by juanitosvq** [comment]
Probably happening because you have a `package.json` in the repository calling the action with invalid JSON e.g. empty file. Reopened in https://github.com/JasonEtco/create-an-issue/issues/194
